# RAG Server WebUI Settings Configuration
# This file contains WebUI-specific settings that can be modified without code changes
# Core server settings (DB, LLM, etc.) are managed in .env file

# Application Settings (WebUI specific)
app:
  title: "RAG Server"  # Can be overridden by RAG_APP_TITLE env var
  icon: "🤖"  # Can be overridden by RAG_APP_ICON env var
  theme: "light"  # Can be overridden by RAG_THEME env var
  version: "1.0.0"

# API Settings (WebUI client configuration)
# Note: base_url is auto-configured from API_HOST and API_PORT in .env
api:
  timeout: 30  # Can be overridden by RAG_API_TIMEOUT env var
  retry_attempts: 3
  retry_delay: 1.0

# Authentication Settings (WebUI specific)
# Note: jwt_secret_key uses SECRET_KEY from .env by default
auth:
  session_timeout: 3600  # Can be overridden by SESSION_TIMEOUT env var
  enable_demo_users: true  # Can be overridden by ENABLE_DEMO_USERS env var
  demo_users:
    admin:
      password: "admin123"
      role: "admin"
      email: "admin@ragserver.local"
      department: "IT"
    user:
      password: "user123"
      role: "user"
      email: "user@ragserver.local"
      department: "General"
    manager:
      password: "manager123"
      role: "manager"
      email: "manager@ragserver.local"
      department: "Operations"

# Upload Settings
upload:
  max_file_size_mb: 100
  allowed_file_types:
    - txt
    - pdf
    - docx
    - xlsx
    - md
    - json
    - csv

# LLM Provider Settings (WebUI display configuration)
# Note: enabled status is auto-configured based on API keys in .env
# Note: default_model is auto-synced from LLM_MODEL in .env for current LLM_PROVIDER
llm_providers:
  openai:
    name: "OpenAI"
    models:  # Available models for selection
      - gpt-4
      - gpt-3.5-turbo
      - gpt-4-turbo
      - gpt-4o
    default_model: "gpt-4"
  anthropic:
    name: "Anthropic"
    models:
      - claude-3-5-sonnet-latest
      - claude-3-haiku
      - claude-3-opus
    default_model: "claude-3-5-sonnet-latest"
  google:
    name: "Google"
    models:
      - gemini-2.0-flash-001
      - gemini-1.5-pro
    default_model: "gemini-2.0-flash-001"
  ollama:
    name: "Ollama"
    models:  # Common models - current model from .env is auto-added
      - llama3.2
      - gemma2
      - mistral
    default_model: "llama3.2"

# Default Query Parameters
query_defaults:
  k: 5
  temperature: 0.7
  max_tokens: 1000
  similarity_threshold: 0.7

# Document Categories
document_categories:
  - name: "General"
    description: "General purpose documents"
    color: "#2196F3"
  - name: "Technical" 
    description: "Technical documentation and manuals"
    color: "#4CAF50"
  - name: "Financial"
    description: "Financial reports and documents"
    color: "#FF9800"
  - name: "Legal"
    description: "Legal documents and contracts"
    color: "#F44336"
  - name: "Marketing"
    description: "Marketing materials and campaigns"
    color: "#E91E63"
  - name: "HR"
    description: "Human resources documents"
    color: "#9C27B0"
  - name: "Operations"
    description: "Operational procedures and guidelines"
    color: "#607D8B"

# Access Levels
access_levels:
  - name: "Public"
    description: "Accessible to all users"
    level: 0
    color: "#4CAF50"
  - name: "Internal"
    description: "Accessible to internal users only"
    level: 1
    color: "#2196F3"
  - name: "Restricted"
    description: "Restricted access - approval required"
    level: 2
    color: "#FF9800"
  - name: "Confidential"
    description: "Confidential - admin access only"
    level: 3
    color: "#F44336"

# User Roles
user_roles:
  user:
    name: "User"
    description: "Standard user with basic access"
    level: 1
    permissions:
      - read_documents
      - query_system
      - view_own_queries
  manager:
    name: "Manager"
    description: "Manager with elevated permissions"
    level: 2
    permissions:
      - read_documents
      - query_system
      - view_own_queries
      - view_team_queries
      - upload_documents
      - manage_team_users
  admin:
    name: "Administrator"
    description: "Full system administrator"
    level: 3
    permissions:
      - read_documents
      - query_system
      - view_all_queries
      - upload_documents
      - manage_all_users
      - system_configuration
      - view_system_logs
      - manage_categories
      - manage_access_levels

# UI Settings
ui:
  items_per_page: 20
  enable_dark_mode: true
  enable_sidebar_collapse: true
  show_advanced_options: false
  enable_file_preview: true
  enable_query_history: true
  max_query_history: 100

# Debug and Logging
debug:
  enabled: false
  log_level: "INFO"
  log_api_calls: false
  show_query_time: true
  show_token_count: true

# Feature Flags
features:
  enable_batch_upload: true
  enable_document_preview: true
  enable_advanced_search: true
  enable_query_suggestions: true
  enable_export_results: true
  enable_user_feedback: true
  enable_analytics: false