[global]
developmentMode = false

[server]
headless = true
port = 8501
address = "localhost"
maxUploadSize = 100
enableCORS = true
enableXsrfProtection = true
# Restrict CORS to local development and production domains
# corsAllowedOriginsList = ["http://localhost:8501", "http://127.0.0.1:8501"]

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"

[client]
toolbarMode = "viewer"

[runner]
magicEnabled = true

[logger]
level = "info"
messageFormat = "%(asctime)s %(message)s"