# Streamlit Secrets Configuration
# Copy this file as secrets.toml and update with your actual values

[webui]
jwt_secret_key = "demo_secret_key_change_in_production"
session_timeout = 3600

[api]
base_url = "http://localhost:8000"
timeout = 30

[demo]
enable_demo_users = true
admin_username = "admin"
admin_password = "admin123"

# Example API keys (replace with your actual keys)
[keys]
openai_api_key = "your-openai-api-key-here"
anthropic_api_key = "your-anthropic-api-key-here"
google_api_key = "your-google-api-key-here"

# Database connection (if needed for direct access)
[database]
host = "localhost"
port = 3306
name = "novelbot"
user = "root"
password = "password"

# Milvus connection (if needed for direct access)
[milvus]
host = "localhost"
port = 19530
user = ""
password = ""